In [5]:
import pandas as pd
Deadline = pd.DataFrame({"source": ["name", "name", "Министерство_обороны","name","name",
                                    "name","name", "name", "name","name", "name", "name"],
                   "quest": ["name", "name", "Строительство_Варп_Портала","name","name",
                             "name","name", "name", "name","name", "name", "name"],
                   "order":["name", "name", "Федеральный_закон","name","name",
                            "name","name", "name", "name","name", "name", "name"],                   
                   "unit": ["name", "name", "Легионы_хаоса","name","name",
                            "name","name", "name", "name","name", "name", "name"],
                   "hero": ["name", "name", "Няшка_Хорус","name","name",
                            "name","name", "name", "name","name", "name", "name"],
                   "deadline": ["name", "name", "Вчера","name","name",
                                "name","name", "name", "name","name", "name", "name"],
                   'source_year': [2015, 2016, 2017,2011, 2017,2017, 2011,2014,2011,2022,2009,2021],
                         'source_month': [2, 3,10,2,3,4,5,12,8,10,11,12],
                         'source_day': [4, 5,19,23,30,29,28,10,14,1,2,11],
                   'quest_year': [2015, 2016, 2017,2011, 2017,2017, 2011,2014,2011,2022,2009,2021],
                         'quest_month': [2, 3,10,2,3,4,5,12,8,10,11,12], 
                         'quest_day': [4, 5,19,23,30,29,28,10,14,1,2,11],
                   'order_year': [2015, 2016, 2017,2011, 2017,2017, 2011,2014,2011,2022,2009,2021],
                         'order_month': [2, 3,10,2,3,4,5,12,8,10,11,12],
                         'order_day': [4, 5,19,23,30,29,28,10,14,1,2,11],
                   'unit_year': [2015, 2016, 2017,2011, 2017,2017, 2011,2014,2011,2022,2009,2021],
                         'unit_month': [2, 3,10,2,3,4,5,12,8,10,11,12], 
                         'unit_day': [2,5,19,23,30,29,28,10,14,1,2,11],
                   'hero_year': [2015, 2016, 2017,2011, 2017,2017, 2011,2014,2011,2022,2009,2021],
                         'hero_month': [2, 3,10,2,3,4,5,12,8,10,11,12], 
                         'hero_day': [1,4,19,23,30,29,28,10,14,1,2,11],
                   'deadline_year': [2015, 2016, 2017,2011, 2017,2017, 2011,2014,2011,2022,2009,2021],
                         'deadline_month': [2, 3,10,2,3,4,5,12,8,10,11,12],
                         'deadline_day': [4, 5,18,23,30,29,28,10,14,1,2,11],
                  })
Deadline = Deadline[['source','source_year','source_month','source_day',"quest",
                     'quest_year','quest_month','quest_day',"order",'order_year',
                     'order_month', 'order_day', "unit",'unit_year', 'unit_month',
                     'unit_day',"hero",'hero_year','hero_month','hero_day',"deadline",
                     'deadline_year','deadline_month','deadline_day']]
Deadline

,source,source_year,source_month,source_day,quest,quest_year,quest_month,quest_day,order,order_year,...,unit_month,unit_day,hero,hero_year,hero_month,hero_day,deadline,deadline_year,deadline_month,deadline_day
0,name,2015,2,4,name,2015,2,4,name,2015,...,2,2,name,2015,2,1,name,2015,2,4
1,name,2016,3,5,name,2016,3,5,name,2016,...,3,5,name,2016,3,4,name,2016,3,5
2,Министерство_обороны,2017,10,19,Строительство_Варп_Портала,2017,10,19,Федеральный_закон,2017,...,10,19,Няшка_Хорус,2017,10,19,Вчера,2017,10,18
3,name,2011,2,23,name,2011,2,23,name,2011,...,2,23,name,2011,2,23,name,2011,2,23
4,name,2017,3,30,name,2017,3,30,name,2017,...,3,30,name,2017,3,30,name,2017,3,30
5,name,2017,4,29,name,2017,4,29,name,2017,...,4,29,name,2017,4,29,name,2017,4,29
6,name,2011,5,28,name,2011,5,28,name,2011,...,5,28,name,2011,5,28,name,2011,5,28
7,name,2014,12,10,name,2014,12,10,name,2014,...,12,10,name,2014,12,10,name,2014,12,10
8,name,2011,8,14,name,2011,8,14,name,2011,...,8,14,name,2011,8,14,name,2011,8,14
9,name,2022,10,1,name,2022,10,1,name,2022,...,10,1,name,2022,10,1,name,2022,10,1
10,name,2009,11,2,name,2009,11,2,name,2009,...,11,2,name,2009,11,2,name,2009,11,2
11,name,2021,12,11,name,2021,12,11,name,2021,...,12,11,name,2021,12,11,name,2021,12,11

In [4]:
Deadline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 24 columns):
source            12 non-null object
source_year       12 non-null int64
source_month      12 non-null int64
source_day        12 non-null int64
quest             12 non-null object
quest_year        12 non-null int64
quest_month       12 non-null int64
quest_day         12 non-null int64
order             12 non-null object
order_year        12 non-null int64
order_month       12 non-null int64
order_day         12 non-null int64
unit              12 non-null object
unit_year         12 non-null int64
unit_month        12 non-null int64
unit_day          12 non-null int64
hero              12 non-null object
hero_year         12 non-null int64
hero_month        12 non-null int64
hero_day          12 non-null int64
deadline          12 non-null object
deadline_year     12 non-null int64
deadline_month    12 non-null int64
deadline_day      12 non-null int64
dtypes: int64(18), object(6)
memory usage: 2.3+ KB

In [ ]:
source - объект, источник данных чтение которых осуществляет система
source_year, source_month, source_day - время записи данных в систему
quest - объект, процесс протекающий в объекте source в рамках правила order
quest_year, quest_month, quest_day - дата постановки задачи в рамках правила order  
order - объект, правило (в виде закона или приказа) которе определяет цели и характер объекта quest
order_year, order_month, order_day - дата формирования правила, которое определяет характер и цели объекта quest
unit - объект, принадлежащий объекту source, подразделение отвечающие за выполнения объекта quest в рамках правила order
unit_year, unit_month, unit_day - дата, время начала работы объекта unit над процессом в объекте quest по правилу объекта order
hero - объект, руководитель объекта unit, руководящее лицо отвечающие за исполнение работы над объектом quest в рамках объекта unit
hero_year, hero_month, hero_day - дата, время начала работы объекта hero в рамках объекта unit над процессом в объекте quest по правилу объекта order
deadline - объект ( на самом деле логический объект True\False где 1 < х; 0 > x где х == deadline_year_month_day ) определяющий успех или неуспех процесса в отведённое время
deadline_year, deadline_month, deadline_day - дата, время запланированное правилом содержащимся в объекте order для завершения процесса quest